/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Draggabletest: typeof import('./components/draggabletest.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    Login: typeof import('./components/Login.vue')['default']
    LoginComponent: typeof import('./components/LoginComponent.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    'LoginForm,': typeof import('./components/LoginForm
    Menu: typeof import('./components/Menu.vue')['default']
    MenuComponent: typeof import('./components/MenuComponent.vue')['default']
    OrderDetail: typeof import('./components/OrderDetail.vue')['default']
    OrderForm: typeof import('./components/OrderForm.vue')['default']
    Register: typeof import('./components/Register.vue')['default']
    RegisterForm: typeof import('./components/RegisterForm.vue')['default']
    RouteDetail: typeof import('./components/RouteDetail.vue')['default']
    RouteDetailForm: typeof import('./components/RouteDetailForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search.vue')['default']
    SearchForm: typeof import('./components/SearchForm.vue')['default']
    SearchTicketForm: typeof import('./components/SearchTicketForm.vue')['default']
    Title: typeof import('./components/Title.vue')['default']
    Train: typeof import('./components/TrainComponent.vue')['default']
    TrainComponent: typeof import('./components/TrainComponent.vue')['default']
    TrainDescription: typeof import('./components/TrainDescription.vue')['default']
    'TrainDescription_dulingxiaodeMacBookPro.local_May170132272023_CaseConflict': typeof import('./components/trainDescription_dulingxiaodeMacBook-Pro.local_May-17-013227-2023_CaseConflict.vue')['default']
    'TrainDescription_dulingxiaodeMacBookPro.local_May170133052023_CaseConflict': typeof import('./components/TrainDescription.vue')['default']
    TrainDetail: typeof import('./components/TrainDetail.vue')['default']
    UserInfoComponent: typeof import('./components/UserInfoComponent.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
